### ISSUE TITLE
Create and maintain a really simple program containing at least one session

### ISSUE THREAD

**Issue by prastoin** [prastoin/bodybuilding-dashboard#3]
# Program builder first step

## Todo 
- [x] Create a page where the user will create a static program
- [x] With auto-generated program name
- [x] The user will only be able to create one program
- [x] The user will only be able to add sessions to the program
- [x] The user will only be able to add exercises to a session
- [x] The user will be able to remove a session from the program
- [x] The user will be able to remove an exercise from a session

## Wireframe:

![image](https://user-images.githubusercontent.com/45004772/178923730-5ac1d451-d64b-4a4f-a181-be12783ae45e.png)

**Comment by prastoin** [comment]
Everything here as been done
