### ISSUE TITLE
Session tracker V0

### ISSUE THREAD

**Issue by prastoin** [prastoin/bodybuilding-dashboard#33]
The first step is to make the user be able to start a session tracker instance from the defined bodybuilding program via the programBuilder.
The first version will be really minimalist:
- The user should be able to start a session tracker instance from the next body building program training session.
- The user will be asked after n each exercise set his performances. This data will be put in an accumulator. Type definition to define
- When the user has finished his session tracker then we will form the moment just display the raw data

For the moment the user should ne be able:
- To skip a training session, exercise, nor set but also not be able to change program exercise oder in the session tracker instance  

Types: ( example )

```ts
interface SetTracker {
   load: number
   repsCounter: number
   setIndex: number
   rest: RestDuration
   rir: number
}

ExerciseTracker {
   exerciseId: string
   setTrackerCollection: SetTracker[]
}

TrainingSessionTracker {
  exerciseTrackerCollection: ExerciseTracker[]
  trainingSessionTrackerId: string
  trainingSessionId: string
}
```

Todo:

- [ ] Create a stack screen for the `sessionTracker` screens
- [ ] Create a `SessionTrackerMachine` that will be invoked in the `appMachine`. Tihs machine should iterate on every trainingSession exercises request for each set the user performances.
- [ ] Create the first wizard entry for the `load`
- [ ] Create the second wizard entry for the `repsCounter`
- [ ] Create the third wizard entry for the `rir`
- [ ] Create the fourth wizard entry for the `rest`
